// This file is auto-generated by @hey-api/openapi-ts

export const $Pet = {
  allOf: [
    {
      $ref: "#/components/schemas/NewPet",
    },
    {
      type: "object",
      required: ["id"],
      properties: {
        id: {
          type: "integer",
          format: "int64",
        },
      },
    },
  ],
} as const;

export const $NewPet = {
  type: "object",
  required: ["name"],
  properties: {
    name: {
      type: "string",
    },
    tag: {
      type: "string",
    },
  },
} as const;

export const $Error = {
  type: "object",
  required: ["code", "message"],
  properties: {
    code: {
      type: "integer",
      format: "int32",
    },
    message: {
      type: "string",
    },
  },
} as const;
