// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise";
import { OpenAPI } from "./core/OpenAPI";
import { request as __request } from "./core/request";
import type {
  AddPetData,
  AddPetResponse,
  DeletePetData,
  DeletePetResponse,
  FindPaginatedPetsData,
  FindPaginatedPetsResponse,
  FindPetByIdData,
  FindPetByIdResponse,
  FindPetsData,
  FindPetsResponse,
  GetNotDefinedResponse,
  PostNotDefinedResponse,
} from "./types.gen";

export class DefaultService {
  /**
   * Returns all pets from the system that the user has access to
   * Nam sed condimentum est. Maecenas tempor sagittis sapien, nec rhoncus sem sagittis sit amet. Aenean at gravida augue, ac iaculis sem. Curabitur odio lorem, ornare eget elementum nec, cursus id lectus. Duis mi turpis, pulvinar ac eros ac, tincidunt varius justo. In hac habitasse platea dictumst. Integer at adipiscing ante, a sagittis ligula. Aenean pharetra tempor ante molestie imperdiet. Vivamus id aliquam diam. Cras quis velit non tortor eleifend sagittis. Praesent at enim pharetra urna volutpat venenatis eget eget mauris. In eleifend fermentum facilisis. Praesent enim enim, gravida ac sodales sed, placerat id erat. Suspendisse lacus dolor, consectetur non augue vel, vehicula interdum libero. Morbi euismod sagittis libero sed lacinia.
   *
   * Sed tempus felis lobortis leo pulvinar rutrum. Nam mattis velit nisl, eu condimentum ligula luctus nec. Phasellus semper velit eget aliquet faucibus. In a mattis elit. Phasellus vel urna viverra, condimentum lorem id, rhoncus nibh. Ut pellentesque posuere elementum. Sed a varius odio. Morbi rhoncus ligula libero, vel eleifend nunc tristique vitae. Fusce et sem dui. Aenean nec scelerisque tortor. Fusce malesuada accumsan magna vel tempus. Quisque mollis felis eu dolor tristique, sit amet auctor felis gravida. Sed libero lorem, molestie sed nisl in, accumsan tempor nisi. Fusce sollicitudin massa ut lacinia mattis. Sed vel eleifend lorem. Pellentesque vitae felis pretium, pulvinar elit eu, euismod sapien.
   *
   * @param data The data for the request.
   * @param data.tags tags to filter by
   * @param data.limit maximum number of results to return
   * @returns Pet pet response
   * @throws ApiError
   */
  public static findPets(
    data: FindPetsData = {},
  ): CancelablePromise<FindPetsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/pets",
      query: {
        tags: data.tags,
        limit: data.limit,
      },
      errors: {
        default: "unexpected error",
      },
    });
  }

  /**
   * Creates a new pet in the store. Duplicates are allowed
   * @param data The data for the request.
   * @param data.requestBody Pet to add to the store
   * @returns Pet pet response
   * @throws ApiError
   */
  public static addPet(data: AddPetData): CancelablePromise<AddPetResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/pets",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        default: "unexpected error",
      },
    });
  }

  /**
   * @deprecated
   * This path is not fully defined.
   * @returns unknown unexpected error
   * @throws ApiError
   */
  public static getNotDefined(): CancelablePromise<GetNotDefinedResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/not-defined",
      errors: {
        default: "unexpected error",
      },
    });
  }

  /**
   * @deprecated
   * This path is not defined at all.
   * @returns unknown unexpected error
   * @throws ApiError
   */
  public static postNotDefined(): CancelablePromise<PostNotDefinedResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/not-defined",
      errors: {
        default: "unexpected error",
      },
    });
  }

  /**
   * Returns a user based on a single ID, if the user does not have access to the pet
   * @param data The data for the request.
   * @param data.id ID of pet to fetch
   * @returns Pet pet response
   * @throws ApiError
   */
  public static findPetById(
    data: FindPetByIdData,
  ): CancelablePromise<FindPetByIdResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/pets/{id}",
      path: {
        id: data.id,
      },
      errors: {
        default: "unexpected error",
      },
    });
  }

  /**
   * deletes a single pet based on the ID supplied
   * @param data The data for the request.
   * @param data.id ID of pet to delete
   * @returns void pet deleted
   * @throws ApiError
   */
  public static deletePet(
    data: DeletePetData,
  ): CancelablePromise<DeletePetResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/pets/{id}",
      path: {
        id: data.id,
      },
      errors: {
        default: "unexpected error",
      },
    });
  }

  /**
   * Returns paginated pets from the system that the user has access to
   *
   * @param data The data for the request.
   * @param data.page page number
   * @param data.tags tags to filter by
   * @param data.limit maximum number of results to return
   * @returns unknown pet response
   * @throws ApiError
   */
  public static findPaginatedPets(
    data: FindPaginatedPetsData = {},
  ): CancelablePromise<FindPaginatedPetsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/paginated-pets",
      query: {
        page: data.page,
        tags: data.tags,
        limit: data.limit,
      },
    });
  }
}
