// This file is auto-generated by @hey-api/openapi-ts

export type Pet = NewPet & {
  id: number;
};

export type NewPet = {
  name: string;
  tag?: string;
};

export type Error = {
  code: number;
  message: string;
};

export type FindPetsData = {
  /**
   * maximum number of results to return
   */
  limit?: number;
  /**
   * tags to filter by
   */
  tags?: Array<string>;
};

export type FindPetsResponse = Array<Pet>;

export type AddPetData = {
  /**
   * Pet to add to the store
   */
  requestBody: NewPet;
};

export type AddPetResponse = Pet;

export type GetNotDefinedResponse = unknown;

export type PostNotDefinedResponse = unknown;

export type FindPetByIdData = {
  /**
   * ID of pet to fetch
   */
  id: number;
};

export type FindPetByIdResponse = Pet;

export type DeletePetData = {
  /**
   * ID of pet to delete
   */
  id: number;
};

export type DeletePetResponse = void;

export type FindPaginatedPetsData = {
  /**
   * maximum number of results to return
   */
  limit?: number;
  /**
   * page number
   */
  page?: number;
  /**
   * tags to filter by
   */
  tags?: Array<string>;
};

export type FindPaginatedPetsResponse = {
  pets?: Array<Pet>;
  nextPage?: number;
};

export type $OpenApiTs = {
  "/pets": {
    get: {
      req: FindPetsData;
      res: {
        /**
         * pet response
         */
        200: Array<Pet>;
        /**
         * unexpected error
         */
        default: Error;
      };
    };
    post: {
      req: AddPetData;
      res: {
        /**
         * pet response
         */
        200: Pet;
        /**
         * unexpected error
         */
        default: Error;
      };
    };
  };
  "/not-defined": {
    get: {
      res: {
        /**
         * unexpected error
         */
        default: unknown;
      };
    };
    post: {
      res: {
        /**
         * unexpected error
         */
        default: unknown;
      };
    };
  };
  "/pets/{id}": {
    get: {
      req: FindPetByIdData;
      res: {
        /**
         * pet response
         */
        200: Pet;
        /**
         * unexpected error
         */
        default: Error;
      };
    };
    delete: {
      req: DeletePetData;
      res: {
        /**
         * pet deleted
         */
        204: void;
        /**
         * unexpected error
         */
        default: Error;
      };
    };
  };
  "/paginated-pets": {
    get: {
      req: FindPaginatedPetsData;
      res: {
        /**
         * pet response
         */
        200: {
          pets?: Array<Pet>;
          nextPage?: number;
        };
      };
    };
  };
};
